version: "3"

services:
  app:
    container_name: "blog-app"
    build:
      context: .
      dockerfile: Dockerfile
    
    ports:
      - "8000:8000"
    
    volumes:
      - ./:/app
    
    command: >
      sh -c "
      python3 manage.py runserver 0.0.0.0:8000
      "