version: "3"

services:
  app:
    container_name: "blog-app"
    build:
      context: .
      dockerfile: Dockerfile
    
    ports:
      - "8000:8000"
    
    volumes:
      - ./:/app
    
    command: >
      sh -c "
      python3 manage.py wait_for_db &&
      python3 manage.py migrate &&
      echo 'CLICK HERE!' 'http://localhost:8001/'  DEV MODE! &&
      python3 manage.py runserver 0.0.0.0:8000
      "

    env_file:
     - .env
    
    depends_on:
     - db

  db:
    image: postgres:latest
    volumes:
      - ./.db/:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=master
      - POSTGRES_USER=blog
      - POSTGRES_PASSWORD=2024blog
    
    ports:
      - "5432:5432"